# SwiftLint Configuration for Brain Waves
# https://github.com/realm/SwiftLint

# Paths to include/exclude from linting
included:
  - BrainWaves
excluded:
  - Pods
  - BrainWaves/BrainWavesTests
  - BrainWaves/BrainWavesUITests
  - .build

# Disabled rules
disabled_rules:
  - trailing_whitespace # Allow trailing whitespace for formatting flexibility
  - todo # Allow TODO comments during development

# Opt-in rules
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 5
  error: 8

type_body_length:
  warning: 300
  error: 500

type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50
  excluded:
    - ID
    - URL
    - UUID

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - x
    - y
    - z
    - i
    - j
    - k
    - to
    - db
    - vm
    - os

cyclomatic_complexity:
  warning: 15
  error: 25
  ignores_case_statements: true

nesting:
  type_level:
    warning: 2
    error: 3
  statement_level:
    warning: 5
    error: 10

file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*?\.swift
                    \/\/  BrainWaves

large_tuple:
  warning: 3
  error: 4

# Custom rules
custom_rules:
  no_print:
    name: "No Print Statements"
    regex: '\bprint\s*\('
    message: "Use Logger instead of print()"
    severity: warning
    excluded: ".*Tests\\.swift"

  no_force_unwrap:
    name: "Avoid Force Unwrap"
    regex: '!\s*(?!is\s|as\s)'
    message: "Avoid force unwrapping. Use optional binding or guard instead"
    severity: warning
    excluded: ".*Tests\\.swift"

  no_swiftui_state_private:
    name: "SwiftUI State Should Be Private"
    regex: '@State\s+(?!private)'
    message: "@State properties should be private"
    severity: warning

reporter: "xcode"
